version: "2.1"
volumes:
    # volume use to share scan data between services - normally mapped to \workspace
    scanners-volume:
        external: false

services: 
    scanner-engine:
        image: meterian/cs-engine:latest
        depends_on: 
            - clair-scanner
            - dagda-server
        volumes:
            - /var/run/docker.sock:/var/run/docker.sock
            - ${DSE_DOCKER_BIN}:${DSE_DOCKER_BIN}
            - scanners-volume:/workspace
            - /tmp:/tmp
        environment: 
            - METERIAN_API_TOKEN=${METERIAN_API_TOKEN}
            - METERIAN_ENV=${METERIAN_ENV}
            - DSE_AISV=v0.7.1
            - MIN_SECURITY=${MIN_SECURITY:-90}
            - MIN_STABILITY=${MIN_STABILITY:-80}
            - MIN_LICENSING=${MIN_LICENSING:-95}
            - DSE_SCAN_TIMEOUT_MINUTES=${DSE_SCAN_TIMEOUT_MINUTES:-}
        ports:
            - "8765:8765"
        networks:
            - dagda-network
            - clair-network

# Clair specific configuration
    clair-db:
        image: arminc/clair-db:latest
        networks:
            - clair-network

    clair-server:
        image: arminc/clair-local-scan:v2.0.6
        restart: always
        links:
            - "clair-db:postgres"
        depends_on: 
            - clair-db
        networks:
            - clair-network

    clair-scanner: 
        image: meterian/cs-clair:latest
        volumes:
            - /var/run/docker.sock:/var/run/docker.sock
            - scanners-volume:/workspace
        depends_on: 
            - clair-server
        network_mode: "service:clair-server"

# Dagda specific configuration
    dagda-server:
        image: meterian/dagda:0.8.1
        networks:
            - dagda-network
        entrypoint: python dagda.py start -s 0.0.0.0 -p 5000 -m dagda-db -mp 27017
        ports:
            - "5000:5000"
        volumes:
            - /var/run/docker.sock:/var/run/docker.sock:ro
            - /tmp:/tmp
        depends_on:
            - dagda-db

    dagda-db:
        image: meterian/cs-dagda-db:latest
        networks:
            - dagda-network
        ports:
            - "27017:27017"

networks: 
    clair-network: 
    dagda-network:
