version: "2.1"
volumes:
    # volume use to share scan data between services - normally mapped to \workspace
    scanners-volume:
        external: false

services: 
    scanner-engine:
        image: meterian/cs-engine:latest
        depends_on: 
            - clair-scanner
        volumes:
            - /var/run/docker.sock:/var/run/docker.sock
            - ${DSE_DOCKER_BIN}:${DSE_DOCKER_BIN}
            - scanners-volume:/workspace
        environment: 
            - METERIAN_API_TOKEN=${METERIAN_API_TOKEN}
            - METERIAN_ENV=${METERIAN_ENV}
            - DSE_AISV=v0.7.1
        ports:
            - "8765:8765"
        networks:
            - clair-network

# Clair specific configuration
    clair-db:
        # investigate how we can ensure that the latest version of the db is always pulled
        # as of issue https://github.com/docker/compose/issues/3574 closed in 2018 the only way to achieve this is by using `docker-compose pull && docker-compose up`.
        # Addition of a pull_policy parameter to service definitions is still being considered :(
        image: arminc/clair-db:latest
        #depends_on: scanner-engine
        networks:
            - clair-network

    clair-server:
        image: arminc/clair-local-scan:v2.0.6
        links:
            - "clair-db:postgres"
        depends_on: 
            - clair-db
        networks:
            - clair-network

    clair-scanner: 
        image: meterian/cs-clair:latest
        volumes:
            - /var/run/docker.sock:/var/run/docker.sock
            - scanners-volume:/workspace
        depends_on: 
            - clair-server
        network_mode: "service:clair-server"

networks: 
    clair-network: 